# Attribute mapping from abbreviations to full names
attribute_mapping = {
    'Wor': 'Work Rate',
    'Vis': 'Vision',
    'Thr': 'Throwing',
    'Tec': 'Technique',
    'Tea': 'Teamwork',
    'Tck': 'Tackling',
    'Str': 'Strength',
    'Sta': 'Stamina',
    'TRO': 'Rushing Out (Tendency)',
    'Ref': 'Reflexes',
    'Pun': 'Punching (Tendency)',
    'Pos': 'Positioning',
    'Pen': 'Penalty Taking',
    'Pas': 'Passing',
    'Pac': 'Pace',
    '1v1': 'One On Ones',
    'OtB': 'Off The Ball',
    'Nat': 'Natural Fitness',
    'Mar': 'Marking',
    'L Th': 'Long Throws',
    'Lon': 'Long Shots',
    'Ldr': 'Leadership',
    'Kic': 'Kicking',
    'Jum': 'Jumping Reach',
    'Hea': 'Heading',
    'Han': 'Handling',
    'Fre': 'Free Kick Taking',
    'Fla': 'Flair',
    'Fir': 'First Touch',
    'Fin': 'Finishing',
    'Ecc': 'Eccentricity',
    'Dri': 'Dribbling',
    'Det': 'Determination',
    'Dec': 'Decision Making',
    'Cro': 'Crossing',
    'Cor': 'Corners',
    'Cnt': 'Concentration',
    'Cmp': 'Composure',
    'Com': 'Communication',
    'Cmd': 'Command Of Area',
    'Bra': 'Bravery',
    'Bal': 'Balance',
    'Ant': 'Anticipation',
    'Agi': 'Agility',
    'Agg': 'Aggression',
    'Aer': 'Aerial Reach',
    'Acc': 'Acceleration',
    'Inf': 'Status',
    'Rec': 'Recovery'
}